self_made_toy/ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls'))
]

self_made_toy/ecom/store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('index', views.index, name='index'),
    path('cart', views.cart, name='cart'),
    path('<int:id>', views.detail, name='detail'),
    path('add/<int:id>', views.show, name='show'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('increase/<int:id>', views.increase, name='increase'),
    path('decrease/<int:id>', views.decrease, name='decrease'),
]

self_made_toy/ecom/store/models.py
from django.db import models
from django.db.models.fields import CharField, IntegerField
from django.shortcuts import get_object_or_404

# Create your models here.


class Item(models.Model):
    name = CharField(max_length=200)
    price = IntegerField()

    def __str__(self):
        return self.name


class Cart(models.Model):
    buy_item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    # def add_to_cart(self, id):
    #     item = Item.objects.get(id=id)
    #     self.objects.create(buy_item=item, quantity=1)

self_made_toy/ecom/store/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

# Create your views here.
from .models import Item
from .models import Cart
# Get all models and display


def index(request):
    items = Item.objects.all()
    context = {'items': items}
    return render(request, 'store/index.html', context)


def show(request, id):
    item = Item.objects.get(id=id)
    # return HttpResponse(item.name)
    ha = Cart.objects.filter(buy_item=item)
    if not ha:
        Cart.objects.create(buy_item=item)
    else:
        current_number = Cart.objects.get(buy_item=item).quantity
        Cart.objects.get(buy_item=item).delete()
        Cart.objects.create(buy_item=item, quantity=current_number+1)
    return cart(request)


def delete(request, id):
    item = Item.objects.get(id=id)
    Cart.objects.get(buy_item=item).delete()
    return cart(request)


def increase(request, id):
    item = Item.objects.get(id=id)
    num = Cart.objects.get(buy_item=item).quantity
    Cart.objects.get(buy_item=item).delete()
    Cart.objects.create(buy_item=item, quantity=num+1)
    return cart(request)


def decrease(request, id):
    item = Item.objects.get(id=id)
    num = Cart.objects.get(buy_item=item).quantity
    Cart.objects.get(buy_item=item).delete()
    Cart.objects.create(buy_item=item, quantity=num-1)
    return cart(request)


def cart(request):
    display = Cart.objects.all()
    context = {'displays': display}
    return render(request, 'store/cart.html', context)


# def addToCart(request, id):
#     Cart.add_to_cart(id=id)
#     Cart.save()
#     items = Cart.objects.all()
#     return render(request, 'store/test.html', {'items': items})


def detail(request, id):
    item = Item.objects.filter(id=id)
    context = {'item': item}
    return render(request, 'store/detail.html', context)

self_made_toy/ecom/templates/store/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Ecommerce - Jiangyan Li</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'store:index' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store:cart' %}">Cart</a>
            </li>
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    <hr />
    <div style="margin-top: 120px"></div>

    <div class="container">{% block content %}{% endblock content %}</div>

    <script src="" async defer></script>
  </body>
</html>

self_made_toy/ecom/templates/store/cart.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Jiangyan Li</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% extends './base.html' %} {% block content %}
    <div class="container"><h1>cart page</h1></div>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">name</th>
          <th scope="col">number</th>
          <th scope="col">Update</th>
          <th scope="col">price</th>
          <th scope="col">delete</th>
        </tr>
      </thead>
      <tbody>
        {% for display in displays %}
        <tr>
          <td>{{display.buy_item.name}}</td>
          <td>{{display.quantity}}</td>
          <td>
            <span>
              <a
                href="{% url 'store:increase' display.buy_item.id %}"
                class="btn btn-warning"
                style="color: red"
                >+1</a
              >
            </span>

            <span>
              <a
                href="{% url 'store:decrease' display.buy_item.id %}"
                class="btn btn-warning"
                style="color: red"
                >-1</a
              >
            </span>
          </td>
          <td>${{display.buy_item.price}}x{{display.quantity}}</td>
          <td>
            <a
              href="{% url 'store:delete' display.buy_item.id %}"
              class="btn btn-warning"
              >delete</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endblock content %}
    <script src="" async defer></script>
  </body>
</html>

self_made_toy/ecom/templates/store/detail.html
{% for i in item %}
<div class="container" style="margin-top: 50px">
  <h1>This is {{i.name}}'s details page.</h1>
  <h1>Even though I can't type all the deatils about it.</h1>
</div>
{% endfor %}

self_made_toy/ecom/templates/store/index.html
{% extends './base.html' %} {% block content %} {% for item in items %}

<div
  class="card"
  style="
    background-color: beige;
    width: 18rem;
    margin: auto;
    margin-bottom: 20px;
  "
>
  <div class="card-body" style="margin: auto">
    <h5 class="card-title" style="font-weight: bold">{{item.name}}</h5>
    <p class="card-text">$ {{item.price}}</p>
    <div class="container" style="margin-bottom: 5px">
      <a
        href="{% url 'store:detail' item.id %}"
        class="btn btn-warning"
        style="color: red"
        >Details</a
      >
    </div>

    <div class="container" style="margin-bottom: 5px">
      <a
        href="{% url 'store:show' item.id  %}"
        class="btn btn-warning"
        style="color: red"
        >Add to Cart</a
      >
    </div>
  </div>
</div>

{% endfor %} {% endblock content %}

self_made_toy/ecom/templates/store/test.html
{% for i in items %} {{i.name}} {% endfor %}